<?php
	#
	# Sources:
	#   http://technet.microsoft.com/en-us/library/cc749073(v=ws.10).aspx (beware, has many mistakes)
	#   http://www.worldtimezone.com/
	#   http://en.wikipedia.org/
	#   http://www.php.net/manual/en/timezones.php
	#   http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
	#   My ailing brain
	#
	# Things to note:
	#   There are many cities called La Paz!
	#

	function timezones_list(){

		return array(
			array('(GMT-11:00) Midway Island, Samoa',				'Pacific/Midway',		'Samoa Standard Time'),
			array('(GMT-10:00) Hawaii',						'Pacific/Honolulu',		'Hawaiian Standard Time'),
			array('(GMT-09:00) Alaska',						'America/Anchorage',		'Alaskan Standard Time'),
			array('(GMT-08:00) Baja California',					'America/Tijuana',		''),
			array('(GMT-08:00) Pacific Time (US and Canada)',			'America/Los_Angeles',		'Pacific Standard Time'),
			array('(GMT-07:00) Arizona',						'America/Phoenix',		'US Mountain Standard Time'),
			array('(GMT-07:00) Chihuahua, La Paz, Mazatlan',			'America/Chihuahua',		'Mountain Standard Time (Mexico)'),
			array('(GMT-07:00) Mountain Time (US and Canada)',			'America/Denver',		'Mountain Standard Time'),
			array('(GMT-06:00) Central America',					'America/Belize',		'Central America Standard Time'),
			array('(GMT-06:00) Central Time (US and Canada)	',			'America/Chicago',		'Central Standard Time'),
			array('(GMT-06:00) Guadalajara, Mexico City, Monterrey',		'America/Mexico_City',		'Central Standard Time (Mexico)'),
			array('(GMT-06:00) Saskatchewan',					'America/Regina',		'Canada Central Standard Time'),
			array('(GMT-05:00) Bogota, Lima, Quito',				'America/Bogota',		'SA Pacific Standard Time'),
			array('(GMT-05:00) Eastern Time (US and Canada)',			'America/New_York',		'Eastern Standard Time'),
			array('(GMT-05:00) Indiana (East)',					'America/Indiana/Indianapolis',	'US Eastern Standard Time'),
			array('(GMT-04:30) Caracas',						'America/Caracas',		''),
			array('(GMT-04:00) Asuncion',						'America/Asuncion',		''),
			array('(GMT-04:00) Atlantic Time (Canada)',				'America/Halifax',		'Atlantic Standard Time'),
			array('(GMT-04:00) Cuiaba',						'America/Cuiaba',		''),
			array('(GMT-04:00) Georgetown, La Paz, Manaus, San Juan',		'America/Manaus',		'SA Western Standard Time / Central Brazilian Standard Time'),
			array('(GMT-04:00) Santiago',						'America/Santiago',		'Pacific SA Standard Time'),
			array('(GMT-03:30) Newfoundland and Labrador',				'America/St_Johns',		'Newfoundland Standard Time'),
			array('(GMT-03:00) Brasilia',						'America/Sao_Paulo',		'E. South America Standard Time'),
			array('(GMT-03:00) Buenos Aires	',					'America/Buenos_Aires',		'SA Eastern Standard Time'),
			array('(GMT-03:00) Cayenne, Fortaleza',					'America/Cayenne',		''),
			array('(GMT-03:00) Greenland',						'America/Godthab',		'Greenland Standard Time'),
			array('(GMT-03:00) Montevideo',						'America/Montevideo',		''),
			array('(GMT-03:00) Salvador',						'America/Bahia',		''),
			array('(GMT-02:00) Mid-Atlantic',					'America/Noronha',		'Mid-Atlantic Standard Time'),
			array('(GMT-01:00) Azores',						'Atlantic/Azores',		'Azores Standard Time'),
			array('(GMT-01:00) Cape Verde Islands',					'Atlantic/Cape_Verde',		'Cape Verde Standard Time'),
			array('(GMT) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London',	'Europe/London',		'GMT Standard Time'),
			array('(GMT) Casablanca, Monrovia',					'Africa/Casablanca',		'Greenwich Standard Time'),
			array('(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',	'Europe/Amsterdam',		'W. Europe Standard Time'),
			array('(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',	'Europe/Belgrade',		'Central Europe Standard Time'),
			array('(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',		'Europe/Brussels',		'Romance Standard Time'),
			array('(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',			'Europe/Warsaw',		'Central European Standard Time'),
			array('(GMT+01:00) West Central Africa',				'Africa/Algiers',		'W. Central Africa Standard Time'),
			array('(GMT+01:00) Windhoek',						'Africa/Windhoek',		'Namibia Standard Time'),
			array('(GMT+02:00) Athens, Bucharest',					'Europe/Athens',		'GTB Standard Time'),
			array('(GMT+02:00) Beirut',						'Asia/Beirut',			''),
			array('(GMT+02:00) Cairo',						'Africa/Cairo',			'Egypt Standard Time'),
			array('(GMT+02:00) Damascus',						'Asia/Damascus',		''),
			array('(GMT+02:00) Eastern Europe',					'EET',				'E. Europe Standard Time'),
			array('(GMT+02:00) Harare, Pretoria',					'Africa/Harare',		'South Africa Standard Time'),
			array('(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius',	'Europe/Helsinki',		'FLE Standard Time'),
			array('(GMT+02:00) Istanbul',						'Asia/Istanbul',		''),
			array('(GMT+02:00) Jerusalem',						'Asia/Jerusalem',		'Israel Standard Time'),
			array('(GMT+03:00) Amman',						'Asia/Amman',			''),
			array('(GMT+03:00) Baghdad',						'Asia/Baghdad',			'Arabic Standard Time'),
			array('(GMT+03:00) Kalinigrad, Minsk',					'Europe/Kaliningrad',		''),
			array('(GMT+03:00) Kuwait, Riyadh',					'Asia/Kuwait',			'Arab Standard Time'),
			array('(GMT+03:00) Nairobi',						'Africa/Nairobi',		'E. Africa Standard Time'),
			array('(GMT+03:30) Tehran',						'Asia/Tehran',			'Iran Standard Time'),
			array('(GMT+04:00) Abu Dhabi, Muscat',					'Asia/Muscat',			'Arabian Standard Time'),
			array('(GMT+04:00) Baku',						'Asia/Baku',			'Azerbaijan Standard Time'),
			array('(GMT+04:00) Moscow, St. Petersburg, Volgograd',			'Europe/Moscow',		'Russian Standard Time'),
			array('(GMT+04:00) Port Louis',						'Indian/Mauritius',		''),
			array('(GMT+04:00) Tblisi',						'Asia/Tbilisi',			'Georgian Standard Time'),
			array('(GMT+04:00) Yerevan',						'Asia/Yerevan',			'Caucasus Standard Time'),
			array('(GMT+04:30) Kabul',						'Asia/Kabul',			'Afghanistan Standard Time'),
			array('(GMT+05:00) Islamabad, Karachi',					'Asia/Karachi',			'West Asia Standard Time'),
			array('(GMT+05:00) Tashkent',						'Asia/Tashkent',		''),
			array('(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',		'Asia/Kolkata',			'India Standard Time'),
			array('(GMT+05:30) Sri Jayawardenepura',				'Asia/Colombo',			'Sri Lanka Standard Time'),
			array('(GMT+05:45) Kathmandu',						'Asia/Katmandu',		'Nepal Standard Time'),
			array('(GMT+06:00) Astana',						'Asia/Almaty',			'Central Asia Standard Time'),
			array('(GMT+06:00) Dhaka',						'Asia/Dhaka',			''),
			array('(GMT+06:00) Ekaterinburg',					'Asia/Yekaterinburg',		'Ekaterinburg Standard Time'),
			array('(GMT+06:30) Yangon (Rangoon)',					'Asia/Rangoon',			'Myanmar Standard Time'),
			array('(GMT+07:00) Bangkok, Hanoi, Jakarta',				'Asia/Bangkok',			'SE Asia Standard Time'),
			array('(GMT+07:00) Novosibirsk',					'Asia/Novosibirsk',		'Omsk Time'),
			array('(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi',		'Asia/Chongqing',		'China Standard Time'),
			array('(GMT+08:00) Krasnoyarsk',					'Asia/Krasnoyarsk',		'North Asia Standard Time'),
			array('(GMT+08:00) Kuala Lumpur, Singapore',				'Asia/Kuala_Lumpur',		'Singapore Standard Time'),
			array('(GMT+08:00) Perth',						'Australia/Perth',		'W. Australia Standard Time'),
			array('(GMT+08:00) Taipei',						'Asia/Taipei',			'Taipei Standard Time'),
			array('(GMT+08:00) Ulaanbaatar',					'Asia/Ulaanbaatar',		'North Asia East Standard Time'),
			array('(GMT+09:00) Irkutsk',						'Asia/Irkutsk',			''),
			array('(GMT+09:00) Osaka, Sapporo, Tokyo',				'Asia/Tokyo',			'Tokyo Standard Time'),
			array('(GMT+09:00) Seoul',						'Asia/Seoul',			'Korea Standard Time'),
			array('(GMT+09:30) Adelaide',						'Australia/Adelaide',		'Cen. Australia Standard Time'),
			array('(GMT+09:30) Darwin',						'Australia/Darwin',		'AUS Central Standard Time'),
			array('(GMT+10:00) Brisbane',						'Australia/Brisbane',		'E. Australia Standard Time'),
			array('(GMT+10:00) Canberra, Melbourne, Sydney',			'Australia/Canberra',		'AUS Eastern Standard Time'),
			array('(GMT+10:00) Guam, Port Moresby',					'Pacific/Guam',			'West Pacific Standard Time'),
			array('(GMT+10:00) Hobart',						'Australia/Hobart',		'Tasmania Standard Time'),
			array('(GMT+10:00) Yakutsk',						'Asia/Yakutsk',			'Yakutsk Standard Time'),
			array('(GMT+11:00) Solomon Islands, New Caledonia',			'Pacific/Guadalcanal',		'Central Pacific Standard Time'),
			array('(GMT+11:00) Vladivostok',					'Asia/Vladivostok',		'Vladivostok Standard Time'),
			array('(GMT+12:00) Auckland, Wellington',				'Pacific/Auckland',		'New Zealand Standard Time'),
			array('(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands',		'Pacific/Fiji',			'Fiji Standard Time'),
			array('(GMT+12:00) Magadan',						'Asia/Magadan',			''),
			array('(GMT+13:00) Nuku\'alofa',					'Pacific/Tongatapu',		'Tonga Standard Time'),
			array('(GMT+13:00) Samoa',						'Pacific/Samoa',		''),
		);
	}

