<?php
	#
	# Sources:
	#   http://technet.microsoft.com/en-us/library/cc749073(v=ws.10).aspx (beware, has many mistakes)
	#   http://www.worldtimezone.com/
	#   http://en.wikipedia.org/
	#   http://www.php.net/manual/en/timezones.php
	#   http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
	#   http://www.timeanddate.com/
	#   My ailing brain
	#
	# Things to note:
	#   There are many cities called La Paz!
	#
	# Fields:
	#   [DROPDOWN-LABEL, TZ-ID, DEFAULT-FOR-OFFSET, LABEL, DST-LABEL]
	#

	timezones_init();

	function timezones_list(){

		return array(
			array('(UTC-11:00) Midway Island, American Samoa',			'Pacific/Midway',		true,	'Samoa Standard Time',			null),
			array('(UTC-10:00) Aleutian Islands',					'America/Adak',			false,	'Hawaii-Aleutian Standard Time',	'Hawaii-Aleutian Daylight Time'),
			array('(UTC-10:00) Hawaii',						'Pacific/Honolulu',		true,	'Hawaii-Aleutian Standard Time',	null),
			array('(UTC-09:30) Marquesas Islands',					'Pacific/Marquesas',		true,	'Marquesas Time',			null),
			array('(UTC-09:00) Alaska',						'America/Anchorage',		false,	'Alaska Standard Time',			'Alaska Daylight Time'),
			array('(UTC-08:00) Baja California',					'America/Tijuana',		false,	'Pacific Standard Time',		'Pacific Daylight Time'),
			array('(UTC-08:00) Pacific Time (US and Canada)',			'America/Los_Angeles',		true,	'Pacific Standard Time',		'Pacific Daylight Time'),
			array('(UTC-07:00) Arizona',						'America/Phoenix',		false,	'Mountain Standard Time',		'Mountain Daylight Time'),
			array('(UTC-07:00) Chihuahua, La Paz, Mazatlan',			'America/Chihuahua',		false,	'Mountain Standard Time',		'Mountain Daylight Time'),
			array('(UTC-07:00) Mountain Time (US and Canada)',			'America/Denver',		true,	'Mountain Standard Time',		'Mountain Daylight Time'),
			array('(UTC-06:00) Central America',					'America/Belize',		false,	'Central Standard Time',		null),
			array('(UTC-06:00) Central Time (US and Canada)	',			'America/Chicago',		true,	'Central Standard Time',		'Central Daylight Time'),
			array('(UTC-06:00) Easter Island',					'Pacific/Easter',		false,	'Easter Island Standard Time',		'Easter Island Summer Time'),
			array('(UTC-06:00) Guadalajara, Mexico City, Monterrey',		'America/Mexico_City',		false,	'Central Standard Time',		'Central Daylight Time'),
			array('(UTC-06:00) Saskatchewan',					'America/Regina',		true,	'Central Standard Time',		'Central Daylight Time'),
			array('(UTC-05:00) Bogota, Lima, Quito',				'America/Bogota',		false,	'South America Pacific Standard Time',	null), # Colombia Time / Peru Time / Ecuador Time
			array('(UTC-05:00) Chetumal',						'America/Cancun',		false,	'Eastern Standard Time',		null),
			array('(UTC-05:00) Eastern Time (US and Canada)',			'America/New_York',		true,	'Eastern Standard Time',		'Eastern Daylight Time'),
			array('(UTC-05:00) Haiti',						'America/Port-au-Prince',	false,	'Eastern Standard Time',		null),
			array('(UTC-05:00) Havana',						'America/Havana',		false,	'Cuba Standard Time',			'Cuba Daylight Time'),
			array('(UTC-05:00) Indiana (East)',					'America/Indiana/Indianapolis',	false,	'Eastern Standard Time',		'Eastern Daylight Time'),
			array('(UTC-04:00) Asuncion',						'America/Asuncion',		false,	'Paraguay Time',			'Paraguay Summer Time'),
			array('(UTC-04:00) Atlantic Time (Canada)',				'America/Halifax',		false,	'Atlantic Standard Time',		'Atlantic Daylight Time'),
			array('(UTC-04:00) Caracas',						'America/Caracas',		false,	'Venezuelan Standard Time',		null),
			array('(UTC-04:00) Cuiaba',						'America/Cuiaba',		false,	'Amazon Time',				'Amazon Summer Time'),
			array('(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',		'America/Manaus',		true,	'Atlantic Standard Time',		null), # Guyana Time / Bolivia Time / Amazon Time
			array('(UTC-04:00) Santiago',						'America/Santiago',		true,	'Chile Standard Time',			'Chile Summer Time'),
			array('(UTC-04:00) Turks and Caicos',					'America/Grand_Turk',		false,	'Atlantic Standard Time',		null),
			array('(UTC-03:30) Newfoundland',					'America/St_Johns',		false,	'Newfoundland Standard Time',		'Newfoundland Daylight Time'),
			array('(UTC-03:00) Araguaina',						'America/Fortaleza',		false,	'Brasilia Time',			null),
			array('(UTC-03:00) Brasilia',						'America/Sao_Paulo',		true,	'Brasilia Time',			'Brasilia Summer Time'),
			array('(UTC-03:00) Cayenne, Fortaleza',					'America/Cayenne',		false,	'French Guiana Time',			null), # also Brasilia Time
			array('(UTC-03:00) City of Buenos Aires',				'America/Buenos_Aires',		true,	'Argentina Time',			null),
			array('(UTC-03:00) Greenland',						'America/Godthab',		false,	'West Greenland Time',			'Western Greenland Summer Time'),
			array('(UTC-03:00) Montevideo',						'America/Montevideo',		false,	'Uruguay Time',				'Uruguay Summer Time'),
			array('(UTC-03:00) Saint Pierre and Miquelon',				'America/Miquelon',		false,	'Pierre & Miquelon Standard Time',	'Pierre & Miquelon Daylight Time'),
			array('(UTC-03:00) Salvador',						'America/Bahia',		false,	'Brasilia Time',			'Brasilia Summer Time'),
			array('(UTC-01:00) Azores',						'Atlantic/Azores',		false,	'Azores Time',				'Azores Summer Time'),
			array('(UTC-01:00) Cabo Verde Islands',					'Atlantic/Cape_Verde',		false,	'Cape Verde Time',			null),
			array('(UTC) Casablanca',						'Africa/Casablanca',		false,	'Western European Time',		'Western European Summer Time'),
			array('(UTC) Dublin, Edinburgh, Lisbon, London',			'Europe/London',		false,	'Greenwich Mean Time',			'British Summer Time'), # lisbon really does WEST in the summer, but is included here
			array('(UTC) Monrovia, Reykjavik',					'Africa/Monrovia',		false,	'Greenwich Mean Time',			null),
			array('(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',	'Europe/Amsterdam',		true,	'Central European Time',		'Central European Summer Time'),
			array('(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',	'Europe/Belgrade',		false,	'Central European Time',		'Central European Summer Time'),
			array('(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',		'Europe/Brussels',		false,	'Central European Time',		'Central European Summer Time'),
			array('(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',			'Europe/Warsaw',		false,	'Central European Time',		'Central European Summer Time'),
			array('(UTC+01:00) West Central Africa',				'Africa/Algiers',		false,	'Central European Time',		null),
			array('(UTC+01:00) Windhoek',						'Africa/Windhoek',		false,	'West Africa Time',			'West Africa Summer Time'),
			array('(UTC+02:00) Amman',						'Asia/Amman',			false,	'Arabia Standard Time',			'Arabia Standard Time'), # uses DST, but has the same name in winter and summer
			array('(UTC+02:00) Athens, Bucharest',					'Europe/Athens',		false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Beirut',						'Asia/Beirut',			false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Cairo',						'Africa/Cairo',			false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Damascus',						'Asia/Damascus',		false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Gaza, Hebron',					'Asia/Gaza',			false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Harare, Pretoria',					'Africa/Harare',		false,	'Central Africa Time',			null),
			array('(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius',	'Europe/Helsinki',		false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Istanbul',						'Asia/Istanbul',		false,	'Eastern European Time',		'Eastern European Summer Time'),
			array('(UTC+02:00) Jerusalem',						'Asia/Jerusalem',		false,	'Israel Standard Time',			'Israel Daylight Time'),
			array('(UTC+02:00) Kaliningrad',					'Europe/Kaliningrad',		false,	'Eastern European Time',		null), # RTZ1
			array('(UTC+02:00) Tripoli',						'Africa/Tripoli',		false,	'Eastern European Time',		null),
			array('(UTC+03:00) Baghdad',						'Asia/Baghdad',			false,	'Arabia Standard Time',			null),
			array('(UTC+03:00) Kuwait, Riyadh',					'Asia/Kuwait',			true,	'Arabia Standard Time',			null),
			array('(UTC+03:00) Minsk',						'Europe/Minsk',			false,	'Further-eastern European Time',	null),
			array('(UTC+03:00) Moscow, St. Petersburg, Volgograd',			'Europe/Moscow',		true,	'Moscow Time',				null), # RTZ2
			array('(UTC+03:00) Nairobi',						'Africa/Nairobi',		false,	'East Africa Time',			null),
			array('(UTC+03:30) Tehran',						'Asia/Tehran',			false,	'Iran Standard Time',			'Iran Daylight Time'),
			array('(UTC+04:00) Abu Dhabi, Muscat',					'Asia/Muscat',			true,	'Gulf Standard Time',			null),
			array('(UTC+04:00) Astrakhan, Ulyanovsk',				'Europe/Astrakhan',		false,	'Moscow Standard Time',			'Moscow Standard Time +1'), # weird name: http://www.timeanddate.com/news/time/russia-astrakhan-time-zone.html
			array('(UTC+04:00) Baku',						'Asia/Baku',			true,	'Azerbaijan Time',			'Azerbaijan Summer Time'),
			array('(UTC+04:00) Izhevsk, Samara',					'Europe/Samara',		false,	'Samara Time',				null), # RTZ3
			array('(UTC+04:00) Port Louis',						'Indian/Mauritius',		false,	'Mauritius Time',			null),
			array('(UTC+04:00) Tbilisi',						'Asia/Tbilisi',			false,	'Georgia Standard Time',		null),
			array('(UTC+04:00) Yerevan',						'Asia/Yerevan',			false,	'Armenia Time',				'Armenia Summer Time'),
			array('(UTC+04:30) Kabul',						'Asia/Kabul',			false,	'Afghanistan Time',			null),
			array('(UTC+05:00) Tashkent, Ashgabat',					'Asia/Tashkent',		true,	'Uzbekistan Time',			null),
			array('(UTC+05:00) Ekaterinburg',					'Asia/Yekaterinburg',		false,	'Yekaterinburg Time',			null), # RTZ4
			array('(UTC+05:00) Islamabad, Karachi',					'Asia/Karachi',			false,	'Pakistan Standard Time',		null),
			array('(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',		'Asia/Kolkata',			false,	'India Standard Time',			null),
			array('(UTC+05:30) Sri Jayawardenepura',				'Asia/Colombo',			false,	'ISri Lanka Standard Time',		null), # matches India Standard Time since 2006
			array('(UTC+05:45) Kathmandu',						'Asia/Katmandu',		false,	'Nepal Time',				null),
			array('(UTC+06:00) Astana',						'Asia/Almaty',			false,	'Alma-Ata Time',			null),
			array('(UTC+06:00) Dhaka',						'Asia/Dhaka',			true,	'Bangladesh Standard Time',		null),
			array('(UTC+06:00) Novosibirsk',					'Asia/Novosibirsk',		false,	'Novosibirsk Time',			null), # RTZ5
			array('(UTC+06:30) Yangon (Rangoon)',					'Asia/Rangoon',			false,	'Myanmar Time',				null),
			array('(UTC+07:00) Bangkok, Hanoi, Jakarta',				'Asia/Bangkok',			false,	'Indochina Time',			null),
			array('(UTC+07:00) Barnaul, Gorno-Altaysk',				'Asia/Barnaul',			false,	'Moscow Standard Time +4',		null),
			array('(UTC+07:00) Hovd',						'Asia/Hovd',			false,	'Hovd Time',				'Hovd Summer Time'),
			array('(UTC+07:00) Krasnoyarsk',					'Asia/Krasnoyarsk',		false,	'Krasnoyarsk Time',			null), # RTZ6
			array('(UTC+07:00) Tomsk',						'Asia/Tomsk',			false,	'Moscow Standard Time +4',		null),
			array('(UTC+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi',		'Asia/Chongqing',		true,	'China Standard Time',			null),
			array('(UTC+08:00) Irkutsk',						'Asia/Irkutsk',			false,	'Irkutsk Time',				null), # RTZ7
			array('(UTC+08:00) Kuala Lumpur, Singapore',				'Asia/Kuala_Lumpur',		false,	'Singapore Standard Time',		null), # Malaysia Time
			array('(UTC+08:00) Perth',						'Australia/Perth',		false,	'Australian Western Standard Time',	null),
			array('(UTC+08:00) Taipei',						'Asia/Taipei',			false,	'Taiwan Standard Time',			null),
			array('(UTC+08:00) Ulaanbaatar',					'Asia/Ulaanbaatar',		true,	'Ulaanbaatar Time',			null),
			array('(UTC+08:30) Pyongyang',						'Asia/Pyongyang',		false,	'Pyongyang Time',			null),
			array('(UTC+08:45) Eucla',						'Australia/Eucla',		false,	'Australian Central Western Standard Time',	null),
			array('(UTC+09:00) Chita',						'Asia/Chita',			false,	'Yakutsk Time',				null),
			array('(UTC+09:00) Osaka, Sapporo, Tokyo',				'Asia/Tokyo',			true,	'Japan Standard Time',			null),
			array('(UTC+09:00) Seoul',						'Asia/Seoul',			false,	'Korea Standard Time',			null),
			array('(UTC+09:00) Yakutsk',						'Asia/Yakutsk',			false,	'Yakutsk Time',				null), # RTZ8
			array('(UTC+09:30) Adelaide',						'Australia/Adelaide',		false,	'Australian Central Standard Time',	'Australian Central Daylight Time'),
			array('(UTC+09:30) Darwin',						'Australia/Darwin',		false,	'Australian Central Standard Time',	'Australian Central Daylight Time'),
			array('(UTC+10:00) Brisbane',						'Australia/Brisbane',		true,	'Australian Eastern Standard Time',	'Australian Eastern Daylight Time'),
			array('(UTC+10:00) Canberra, Melbourne, Sydney',			'Australia/Canberra',		true,	'Australian Eastern Standard Time',	'Australian Eastern Daylight Time'),
			array('(UTC+10:00) Guam, Port Moresby',					'Pacific/Guam',			false,	'West Pacific Standard Time',		null), # Chamorro Standard Time / Papua New Guinea Time
			array('(UTC+10:00) Hobart',						'Australia/Hobart',		false,	'Australian Eastern Standard Time',	'Australian Eastern Daylight Time'),
			array('(UTC+10:00) Vladivostok',					'Asia/Vladivostok',		false,	'Vladivostok Time',			null), # RTZ9
			array('(UTC+10:30) Lord Howe Island',					'Australia/Lord_Howe',		false,	'Lord Howe Standard Time',		'Lord Howe Daylight Time'),
			array('(UTC+11:00) Bougainville Island',				'Pacific/Bougainville',		false,	'Bougainville Standard Time',		null),
			array('(UTC+11:00) Chokirdakh',						'Asia/Srednekolymsk',		false,	'Srednekolymsk Time',			null), # RTZ10
			array('(UTC+11:00) Magadan',						'Asia/Magadan',			false,	'Magadan Time',				null),
			array('(UTC+11:00) Norfolk Island',					'Pacific/Norfolk',		false,	'Norfolk Time',				null),
			array('(UTC+11:00) Sakhalin',						'Asia/Sakhalin',		false,	'Sakhalin Time',			null),
			array('(UTC+11:00) Solomon Islands, New Caledonia',			'Pacific/Guadalcanal',		false,	'Central Pacific Standard Time',	null), # Solomon IslandsTime / New Caledonia Time
			array('(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky',			'Asia/Anadyr',			false,	'Kamchatka Time',			null), # RTZ11
			array('(UTC+12:00) Auckland, Wellington',				'Pacific/Auckland',		false,	'New Zealand Standard Time',		'New Zealand Daylight Time'),
			array('(UTC+12:00) Fiji Islands',					'Pacific/Fiji',			false,	'Fiji Time',				'Fiji Summer Time'),
			array('(UTC+12:45) Chatham Islands',					'Pacific/Chatham',		false,	'Chatham Island Standard Time',		'Chatham Island Daylight Time'),
			array('(UTC+13:00) Nuku\'alofa',					'Pacific/Tongatapu',		false,	'Tonga Standard Time',			null),
			array('(UTC+13:00) Samoa',						'Pacific/Apia',			false,	'West Samoa Time',			null), # DST name is same as non
			array('(UTC+14:00) Kiritimati Island',					'Pacific/Kiritimati',		false,	'Line Islands Time',			null),
		);
	}

	function timezones_equiv(){

		# automatically built equivs list
		$map = array(
			"Africa/Abidjan" => "Africa/Monrovia",
			"Africa/Accra" => "Africa/Monrovia",
			"Africa/Addis_Ababa" => "Europe/Moscow",
			"Africa/Asmara" => "Europe/Moscow",
			"Africa/Asmera" => "Europe/Moscow",
			"Africa/Bamako" => "Africa/Monrovia",
			"Africa/Bangui" => "Africa/Algiers",
			"Africa/Banjul" => "Africa/Monrovia",
			"Africa/Bissau" => "Africa/Monrovia",
			"Africa/Blantyre" => "Africa/Harare",
			"Africa/Brazzaville" => "Africa/Algiers",
			"Africa/Bujumbura" => "Africa/Harare",
			"Africa/Ceuta" => "Europe/Amsterdam",
			"Africa/Conakry" => "Africa/Monrovia",
			"Africa/Dakar" => "Africa/Monrovia",
			"Africa/Dar_es_Salaam" => "Europe/Moscow",
			"Africa/Djibouti" => "Europe/Moscow",
			"Africa/Douala" => "Africa/Algiers",
			"Africa/El_Aaiun" => "Africa/Casablanca",
			"Africa/Freetown" => "Africa/Monrovia",
			"Africa/Gaborone" => "Africa/Harare",
			"Africa/Johannesburg" => "Africa/Harare",
			"Africa/Juba" => "Europe/Moscow",
			"Africa/Kampala" => "Europe/Moscow",
			"Africa/Khartoum" => "Europe/Moscow",
			"Africa/Kigali" => "Africa/Harare",
			"Africa/Kinshasa" => "Africa/Algiers",
			"Africa/Lagos" => "Africa/Algiers",
			"Africa/Libreville" => "Africa/Algiers",
			"Africa/Lome" => "Africa/Monrovia",
			"Africa/Luanda" => "Africa/Algiers",
			"Africa/Lubumbashi" => "Africa/Harare",
			"Africa/Lusaka" => "Africa/Harare",
			"Africa/Malabo" => "Africa/Algiers",
			"Africa/Maputo" => "Africa/Harare",
			"Africa/Maseru" => "Africa/Harare",
			"Africa/Mbabane" => "Africa/Harare",
			"Africa/Mogadishu" => "Europe/Moscow",
			"Africa/Ndjamena" => "Africa/Algiers",
			"Africa/Niamey" => "Africa/Algiers",
			"Africa/Nouakchott" => "Africa/Monrovia",
			"Africa/Ouagadougou" => "Africa/Monrovia",
			"Africa/Porto-Novo" => "Africa/Algiers",
			"Africa/Sao_Tome" => "Africa/Monrovia",
			"Africa/Timbuktu" => "Africa/Monrovia",
			"Africa/Tunis" => "Africa/Algiers",
			"America/Anguilla" => "America/Manaus",
			"America/Antigua" => "America/Manaus",
			"America/Araguaina" => "America/Buenos_Aires",
			"America/Argentina/Buenos_Aires" => "America/Buenos_Aires",
			"America/Argentina/Catamarca" => "America/Buenos_Aires",
			"America/Argentina/ComodRivadavia" => "America/Buenos_Aires",
			"America/Argentina/Cordoba" => "America/Buenos_Aires",
			"America/Argentina/Jujuy" => "America/Buenos_Aires",
			"America/Argentina/La_Rioja" => "America/Buenos_Aires",
			"America/Argentina/Mendoza" => "America/Buenos_Aires",
			"America/Argentina/Rio_Gallegos" => "America/Buenos_Aires",
			"America/Argentina/Salta" => "America/Buenos_Aires",
			"America/Argentina/San_Juan" => "America/Buenos_Aires",
			"America/Argentina/San_Luis" => "America/Buenos_Aires",
			"America/Argentina/Tucuman" => "America/Buenos_Aires",
			"America/Argentina/Ushuaia" => "America/Buenos_Aires",
			"America/Aruba" => "America/Manaus",
			"America/Atikokan" => "America/Bogota",
			"America/Atka" => "America/Adak",
			"America/Bahia_Banderas" => "America/Mexico_City",
			"America/Barbados" => "America/Manaus",
			"America/Belem" => "America/Buenos_Aires",
			"America/Blanc-Sablon" => "America/Manaus",
			"America/Boa_Vista" => "America/Manaus",
			"America/Boise" => "America/Denver",
			"America/Cambridge_Bay" => "America/Denver",
			"America/Campo_Grande" => "America/Cuiaba",
			"America/Catamarca" => "America/Buenos_Aires",
			"America/Cayman" => "America/Bogota",
			"America/Coral_Harbour" => "America/Bogota",
			"America/Cordoba" => "America/Buenos_Aires",
			"America/Costa_Rica" => "America/Regina",
			"America/Creston" => "America/Phoenix",
			"America/Curacao" => "America/Manaus",
			"America/Danmarkshavn" => "Africa/Monrovia",
			"America/Dawson" => "America/Los_Angeles",
			"America/Dawson_Creek" => "America/Phoenix",
			"America/Detroit" => "America/New_York",
			"America/Dominica" => "America/Manaus",
			"America/Edmonton" => "America/Denver",
			"America/Eirunepe" => "America/Bogota",
			"America/El_Salvador" => "America/Regina",
			"America/Ensenada" => "America/Los_Angeles",
			"America/Fort_Wayne" => "America/New_York",
			"America/Glace_Bay" => "America/Halifax",
			"America/Goose_Bay" => "America/Halifax",
			"America/Grenada" => "America/Manaus",
			"America/Guadeloupe" => "America/Manaus",
			"America/Guatemala" => "America/Regina",
			"America/Guayaquil" => "America/Bogota",
			"America/Guyana" => "America/Manaus",
			"America/Hermosillo" => "America/Phoenix",
			"America/Indiana/Knox" => "America/Chicago",
			"America/Indiana/Marengo" => "America/New_York",
			"America/Indiana/Petersburg" => "America/New_York",
			"America/Indiana/Tell_City" => "America/Chicago",
			"America/Indiana/Vevay" => "America/New_York",
			"America/Indiana/Vincennes" => "America/New_York",
			"America/Indiana/Winamac" => "America/New_York",
			"America/Indianapolis" => "America/New_York",
			"America/Inuvik" => "America/Denver",
			"America/Iqaluit" => "America/New_York",
			"America/Jamaica" => "America/Bogota",
			"America/Jujuy" => "America/Buenos_Aires",
			"America/Juneau" => "America/Anchorage",
			"America/Kentucky/Louisville" => "America/New_York",
			"America/Kentucky/Monticello" => "America/New_York",
			"America/Knox_IN" => "America/Chicago",
			"America/Kralendijk" => "America/Manaus",
			"America/La_Paz" => "America/Manaus",
			"America/Lima" => "America/Bogota",
			"America/Louisville" => "America/New_York",
			"America/Lower_Princes" => "America/Manaus",
			"America/Maceio" => "America/Buenos_Aires",
			"America/Managua" => "America/Regina",
			"America/Marigot" => "America/Manaus",
			"America/Martinique" => "America/Manaus",
			"America/Matamoros" => "America/Chicago",
			"America/Mazatlan" => "America/Chihuahua",
			"America/Mendoza" => "America/Buenos_Aires",
			"America/Menominee" => "America/Chicago",
			"America/Merida" => "America/Mexico_City",
			"America/Moncton" => "America/Halifax",
			"America/Monterrey" => "America/Mexico_City",
			"America/Montreal" => "America/New_York",
			"America/Montserrat" => "America/Manaus",
			"America/Nassau" => "America/New_York",
			"America/Nipigon" => "America/New_York",
			"America/Nome" => "America/Anchorage",
			"America/North_Dakota/Beulah" => "America/Chicago",
			"America/North_Dakota/Center" => "America/Chicago",
			"America/North_Dakota/New_Salem" => "America/Chicago",
			"America/Ojinaga" => "America/Denver",
			"America/Panama" => "America/Bogota",
			"America/Pangnirtung" => "America/New_York",
			"America/Paramaribo" => "America/Buenos_Aires",
			"America/Port_of_Spain" => "America/Manaus",
			"America/Porto_Acre" => "America/Bogota",
			"America/Porto_Velho" => "America/Manaus",
			"America/Puerto_Rico" => "America/Manaus",
			"America/Rainy_River" => "America/Chicago",
			"America/Rankin_Inlet" => "America/Chicago",
			"America/Recife" => "America/Buenos_Aires",
			"America/Resolute" => "America/Chicago",
			"America/Rio_Branco" => "America/Bogota",
			"America/Rosario" => "America/Buenos_Aires",
			"America/Santa_Isabel" => "America/Los_Angeles",
			"America/Santarem" => "America/Buenos_Aires",
			"America/Santo_Domingo" => "America/Manaus",
			"America/Scoresbysund" => "Atlantic/Azores",
			"America/Shiprock" => "America/Denver",
			"America/Sitka" => "America/Anchorage",
			"America/St_Barthelemy" => "America/Manaus",
			"America/St_Kitts" => "America/Manaus",
			"America/St_Lucia" => "America/Manaus",
			"America/St_Thomas" => "America/Manaus",
			"America/St_Vincent" => "America/Manaus",
			"America/Swift_Current" => "America/Regina",
			"America/Tegucigalpa" => "America/Regina",
			"America/Thule" => "America/Halifax",
			"America/Thunder_Bay" => "America/New_York",
			"America/Toronto" => "America/New_York",
			"America/Tortola" => "America/Manaus",
			"America/Vancouver" => "America/Los_Angeles",
			"America/Virgin" => "America/Manaus",
			"America/Whitehorse" => "America/Los_Angeles",
			"America/Winnipeg" => "America/Chicago",
			"America/Yakutat" => "America/Anchorage",
			"America/Yellowknife" => "America/Denver",
			"Antarctica/Casey" => "Asia/Chongqing",
			"Antarctica/Davis" => "Asia/Bangkok",
			"Antarctica/DumontDUrville" => "Australia/Brisbane",
			"Antarctica/Macquarie" => "Pacific/Bougainville",
			"Antarctica/Mawson" => "Asia/Tashkent",
			"Antarctica/McMurdo" => "Pacific/Auckland",
			"Antarctica/Palmer" => "America/Santiago",
			"Antarctica/Rothera" => "America/Buenos_Aires",
			"Antarctica/South_Pole" => "Pacific/Auckland",
			"Antarctica/Syowa" => "Europe/Moscow",
			"Antarctica/Vostok" => "Asia/Dhaka",
			"Arctic/Longyearbyen" => "Europe/Amsterdam",
			"Asia/Aden" => "Europe/Moscow",
			"Asia/Aqtau" => "Asia/Tashkent",
			"Asia/Aqtobe" => "Asia/Tashkent",
			"Asia/Ashgabat" => "Asia/Tashkent",
			"Asia/Ashkhabad" => "Asia/Tashkent",
			"Asia/Bahrain" => "Europe/Moscow",
			"Asia/Bishkek" => "Asia/Dhaka",
			"Asia/Brunei" => "Asia/Chongqing",
			"Asia/Calcutta" => "Asia/Kolkata",
			"Asia/Choibalsan" => "Asia/Ulaanbaatar",
			"Asia/Chungking" => "Asia/Chongqing",
			"Asia/Dacca" => "Asia/Dhaka",
			"Asia/Dili" => "Asia/Tokyo",
			"Asia/Dubai" => "Asia/Muscat",
			"Asia/Dushanbe" => "Asia/Tashkent",
			"Asia/Harbin" => "Asia/Chongqing",
			"Asia/Hebron" => "Asia/Gaza",
			"Asia/Ho_Chi_Minh" => "Asia/Bangkok",
			"Asia/Hong_Kong" => "Asia/Chongqing",
			"Asia/Jakarta" => "Asia/Bangkok",
			"Asia/Jayapura" => "Asia/Tokyo",
			"Asia/Kamchatka" => "Asia/Anadyr",
			"Asia/Kashgar" => "Asia/Dhaka",
			"Asia/Kathmandu" => "Asia/Katmandu",
			"Asia/Khandyga" => "Asia/Tokyo",
			"Asia/Kuching" => "Asia/Chongqing",
			"Asia/Macao" => "Asia/Chongqing",
			"Asia/Macau" => "Asia/Chongqing",
			"Asia/Makassar" => "Asia/Chongqing",
			"Asia/Manila" => "Asia/Chongqing",
			"Asia/Nicosia" => "Europe/Athens",
			"Asia/Novokuznetsk" => "Asia/Bangkok",
			"Asia/Omsk" => "Asia/Dhaka",
			"Asia/Oral" => "Asia/Tashkent",
			"Asia/Phnom_Penh" => "Asia/Bangkok",
			"Asia/Pontianak" => "Asia/Bangkok",
			"Asia/Qatar" => "Europe/Moscow",
			"Asia/Qyzylorda" => "Asia/Dhaka",
			"Asia/Riyadh" => "Europe/Moscow",
			"Asia/Saigon" => "Asia/Bangkok",
			"Asia/Samarkand" => "Asia/Tashkent",
			"Asia/Shanghai" => "Asia/Chongqing",
			"Asia/Singapore" => "Asia/Chongqing",
			"Asia/Tel_Aviv" => "Asia/Jerusalem",
			"Asia/Thimbu" => "Asia/Dhaka",
			"Asia/Thimphu" => "Asia/Dhaka",
			"Asia/Ujung_Pandang" => "Asia/Chongqing",
			"Asia/Ulan_Bator" => "Asia/Ulaanbaatar",
			"Asia/Urumqi" => "Asia/Dhaka",
			"Asia/Ust-Nera" => "Australia/Brisbane",
			"Asia/Vientiane" => "Asia/Bangkok",
			"Atlantic/Bermuda" => "America/Halifax",
			"Atlantic/Canary" => "Europe/London",
			"Atlantic/Faeroe" => "Europe/London",
			"Atlantic/Faroe" => "Europe/London",
			"Atlantic/Jan_Mayen" => "Europe/Amsterdam",
			"Atlantic/Madeira" => "Europe/London",
			"Atlantic/Reykjavik" => "Africa/Monrovia",
			"Atlantic/St_Helena" => "Africa/Monrovia",
			"Atlantic/Stanley" => "America/Buenos_Aires",
			"Australia/ACT" => "Australia/Canberra",
			"Australia/Broken_Hill" => "Australia/Adelaide",
			"Australia/Currie" => "Australia/Canberra",
			"Australia/LHI" => "Australia/Lord_Howe",
			"Australia/Lindeman" => "Australia/Brisbane",
			"Australia/Melbourne" => "Australia/Canberra",
			"Australia/NSW" => "Australia/Canberra",
			"Australia/North" => "Australia/Darwin",
			"Australia/Queensland" => "Australia/Brisbane",
			"Australia/South" => "Australia/Adelaide",
			"Australia/Sydney" => "Australia/Canberra",
			"Australia/Tasmania" => "Australia/Canberra",
			"Australia/Victoria" => "Australia/Canberra",
			"Australia/West" => "Asia/Chongqing",
			"Australia/Yancowinna" => "Australia/Adelaide",
			"Brazil/Acre" => "America/Bogota",
			"Brazil/East" => "America/Sao_Paulo",
			"Brazil/West" => "America/Manaus",
			"CET" => "Europe/Amsterdam",
			"CST6CDT" => "America/Chicago",
			"Canada/Atlantic" => "America/Halifax",
			"Canada/Central" => "America/Chicago",
			"Canada/East-Saskatchewan" => "America/Regina",
			"Canada/Eastern" => "America/New_York",
			"Canada/Mountain" => "America/Denver",
			"Canada/Newfoundland" => "America/St_Johns",
			"Canada/Pacific" => "America/Los_Angeles",
			"Canada/Saskatchewan" => "America/Regina",
			"Canada/Yukon" => "America/Los_Angeles",
			"Chile/Continental" => "America/Santiago",
			"Chile/EasterIsland" => "Pacific/Easter",
			"Cuba" => "America/Havana",
			"EET" => "Europe/Athens",
			"EST" => "America/New_York",
			"EST5EDT" => "America/New_York",
			"Egypt" => "Africa/Cairo",
			"Eire" => "Europe/London",
			"Etc/GMT" => "Africa/Monrovia",
			"Etc/GMT+0" => "Africa/Monrovia",
			"Etc/GMT+1" => "Atlantic/Cape_Verde",
			"Etc/GMT+10" => "Pacific/Honolulu",
			"Etc/GMT+11" => "Pacific/Midway",
			"Etc/GMT+3" => "America/Buenos_Aires",
			"Etc/GMT+4" => "America/Manaus",
			"Etc/GMT+5" => "America/Bogota",
			"Etc/GMT+6" => "America/Regina",
			"Etc/GMT+7" => "America/Phoenix",
			"Etc/GMT-0" => "Africa/Monrovia",
			"Etc/GMT-1" => "Africa/Algiers",
			"Etc/GMT-10" => "Australia/Brisbane",
			"Etc/GMT-11" => "Pacific/Bougainville",
			"Etc/GMT-12" => "Asia/Anadyr",
			"Etc/GMT-13" => "Pacific/Tongatapu",
			"Etc/GMT-14" => "Pacific/Kiritimati",
			"Etc/GMT-2" => "Africa/Harare",
			"Etc/GMT-3" => "Europe/Moscow",
			"Etc/GMT-4" => "Asia/Muscat",
			"Etc/GMT-5" => "Asia/Tashkent",
			"Etc/GMT-6" => "Asia/Dhaka",
			"Etc/GMT-7" => "Asia/Bangkok",
			"Etc/GMT-8" => "Asia/Chongqing",
			"Etc/GMT-9" => "Asia/Tokyo",
			"Etc/GMT0" => "Africa/Monrovia",
			"Etc/Greenwich" => "Africa/Monrovia",
			"Etc/UCT" => "Africa/Monrovia",
			"Etc/UTC" => "Africa/Monrovia",
			"Etc/Universal" => "Africa/Monrovia",
			"Etc/Zulu" => "Africa/Monrovia",
			"Europe/Andorra" => "Europe/Amsterdam",
			"Europe/Belfast" => "Europe/London",
			"Europe/Berlin" => "Europe/Amsterdam",
			"Europe/Bratislava" => "Europe/Amsterdam",
			"Europe/Bucharest" => "Europe/Athens",
			"Europe/Budapest" => "Europe/Amsterdam",
			"Europe/Busingen" => "Europe/Amsterdam",
			"Europe/Copenhagen" => "Europe/Amsterdam",
			"Europe/Dublin" => "Europe/London",
			"Europe/Gibraltar" => "Europe/Amsterdam",
			"Europe/Guernsey" => "Europe/London",
			"Europe/Isle_of_Man" => "Europe/London",
			"Europe/Istanbul" => "Asia/Istanbul",
			"Europe/Jersey" => "Europe/London",
			"Europe/Kiev" => "Europe/Athens",
			"Europe/Kirov" => "Europe/Moscow",
			"Europe/Lisbon" => "Europe/London",
			"Europe/Ljubljana" => "Europe/Amsterdam",
			"Europe/Luxembourg" => "Europe/Amsterdam",
			"Europe/Madrid" => "Europe/Amsterdam",
			"Europe/Malta" => "Europe/Amsterdam",
			"Europe/Mariehamn" => "Europe/Athens",
			"Europe/Monaco" => "Europe/Amsterdam",
			"Europe/Nicosia" => "Europe/Athens",
			"Europe/Oslo" => "Europe/Amsterdam",
			"Europe/Paris" => "Europe/Amsterdam",
			"Europe/Podgorica" => "Europe/Amsterdam",
			"Europe/Prague" => "Europe/Amsterdam",
			"Europe/Riga" => "Europe/Athens",
			"Europe/Rome" => "Europe/Amsterdam",
			"Europe/San_Marino" => "Europe/Amsterdam",
			"Europe/Sarajevo" => "Europe/Amsterdam",
			"Europe/Simferopol" => "Europe/Moscow",
			"Europe/Skopje" => "Europe/Amsterdam",
			"Europe/Sofia" => "Europe/Athens",
			"Europe/Stockholm" => "Europe/Amsterdam",
			"Europe/Tallinn" => "Europe/Athens",
			"Europe/Tirane" => "Europe/Amsterdam",
			"Europe/Ulyanovsk" => "Europe/Astrakhan",
			"Europe/Uzhgorod" => "Europe/Athens",
			"Europe/Vaduz" => "Europe/Amsterdam",
			"Europe/Vatican" => "Europe/Amsterdam",
			"Europe/Vienna" => "Europe/Amsterdam",
			"Europe/Vilnius" => "Europe/Athens",
			"Europe/Volgograd" => "Europe/Moscow",
			"Europe/Zagreb" => "Europe/Amsterdam",
			"Europe/Zaporozhye" => "Europe/Athens",
			"Europe/Zurich" => "Europe/Amsterdam",
			"Factory" => "Africa/Monrovia",
			"GB" => "Europe/London",
			"GB-Eire" => "Europe/London",
			"GMT" => "Africa/Monrovia",
			"GMT+0" => "Africa/Monrovia",
			"GMT-0" => "Africa/Monrovia",
			"GMT0" => "Africa/Monrovia",
			"Greenwich" => "Africa/Monrovia",
			"HST" => "Pacific/Honolulu",
			"Hongkong" => "Asia/Chongqing",
			"Iceland" => "Africa/Monrovia",
			"Indian/Antananarivo" => "Europe/Moscow",
			"Indian/Chagos" => "Asia/Dhaka",
			"Indian/Christmas" => "Asia/Bangkok",
			"Indian/Cocos" => "Asia/Rangoon",
			"Indian/Comoro" => "Europe/Moscow",
			"Indian/Kerguelen" => "Asia/Tashkent",
			"Indian/Mahe" => "Asia/Muscat",
			"Indian/Maldives" => "Asia/Tashkent",
			"Indian/Mayotte" => "Europe/Moscow",
			"Indian/Reunion" => "Asia/Muscat",
			"Iran" => "Asia/Tehran",
			"Israel" => "Asia/Jerusalem",
			"Jamaica" => "America/Bogota",
			"Japan" => "Asia/Tokyo",
			"Kwajalein" => "Asia/Anadyr",
			"Libya" => "Africa/Harare",
			"MET" => "Europe/Amsterdam",
			"MST" => "America/Denver",
			"MST7MDT" => "America/Denver",
			"Mexico/BajaNorte" => "America/Los_Angeles",
			"Mexico/BajaSur" => "America/Chihuahua",
			"Mexico/General" => "America/Mexico_City",
			"NZ" => "Pacific/Auckland",
			"NZ-CHAT" => "Pacific/Chatham",
			"Navajo" => "America/Denver",
			"PRC" => "Asia/Chongqing",
			"PST8PDT" => "America/Los_Angeles",
			"Pacific/Chuuk" => "Australia/Brisbane",
			"Pacific/Efate" => "Pacific/Bougainville",
			"Pacific/Enderbury" => "Pacific/Tongatapu",
			"Pacific/Fakaofo" => "Pacific/Tongatapu",
			"Pacific/Funafuti" => "Asia/Anadyr",
			"Pacific/Galapagos" => "America/Regina",
			"Pacific/Johnston" => "Pacific/Honolulu",
			"Pacific/Kosrae" => "Pacific/Bougainville",
			"Pacific/Kwajalein" => "Asia/Anadyr",
			"Pacific/Majuro" => "Asia/Anadyr",
			"Pacific/Nauru" => "Asia/Anadyr",
			"Pacific/Niue" => "Pacific/Midway",
			"Pacific/Noumea" => "Pacific/Bougainville",
			"Pacific/Pago_Pago" => "Pacific/Midway",
			"Pacific/Palau" => "Asia/Tokyo",
			"Pacific/Pohnpei" => "Pacific/Bougainville",
			"Pacific/Ponape" => "Pacific/Bougainville",
			"Pacific/Port_Moresby" => "Australia/Brisbane",
			"Pacific/Rarotonga" => "Pacific/Honolulu",
			"Pacific/Saipan" => "Australia/Brisbane",
			"Pacific/Samoa" => "Pacific/Midway",
			"Pacific/Tahiti" => "Pacific/Honolulu",
			"Pacific/Tarawa" => "Asia/Anadyr",
			"Pacific/Truk" => "Australia/Brisbane",
			"Pacific/Wake" => "Asia/Anadyr",
			"Pacific/Wallis" => "Asia/Anadyr",
			"Pacific/Yap" => "Australia/Brisbane",
			"Poland" => "Europe/Amsterdam",
			"Portugal" => "Europe/London",
			"ROC" => "Asia/Chongqing",
			"ROK" => "Asia/Tokyo",
			"Singapore" => "Asia/Chongqing",
			"Turkey" => "Asia/Istanbul",
			"UCT" => "Africa/Monrovia",
			"US/Alaska" => "America/Anchorage",
			"US/Aleutian" => "America/Adak",
			"US/Arizona" => "America/Phoenix",
			"US/Central" => "America/Chicago",
			"US/East-Indiana" => "America/New_York",
			"US/Eastern" => "America/New_York",
			"US/Hawaii" => "Pacific/Honolulu",
			"US/Indiana-Starke" => "America/Chicago",
			"US/Michigan" => "America/New_York",
			"US/Mountain" => "America/Denver",
			"US/Pacific" => "America/Los_Angeles",
			"US/Pacific-New" => "America/Los_Angeles",
			"US/Samoa" => "Pacific/Midway",
			"UTC" => "Africa/Monrovia",
			"Universal" => "Africa/Monrovia",
			"W-SU" => "Europe/Moscow",
			"WET" => "Europe/Amsterdam",
			"Zulu" => "Africa/Monrovia",
		);


		# manual overrides
		$map["America/Guatemala"]	= "America/Belize";
		$map["America/Indianapolis"]	= "America/Indiana/Indianapolis";
		$map["America/La_Paz"]		= "America/Manaus";
		$map["UTC"]			= "Africa/Monrovia";
		$map["Atlantic/Reykjavik"]	= "Africa/Monrovia";
		$map["Europe/Berlin"]		= "Europe/Amsterdam";
		$map["Europe/Budapest"]		= "Europe/Belgrade";
		$map["Europe/Paris"]		= "Europe/Brussels";
		$map["Africa/Lagos"]		= "Africa/Algiers";
		$map["Europe/Bucharest"]	= "Europe/Athens";
		$map["Africa/Johannesburg"]	= "Africa/Harare";
		$map["Europe/Kiev"]		= "Europe/Helsinki";
		$map["Europe/Istanbul"]		= "Asia/Istanbul";
		$map["Asia/Riyadh"]		= "Asia/Kuwait";
		$map["Asia/Dubai"]		= "Asia/Muscat";
		$map["Asia/Calcutta"]		= "Asia/Kolkata";
		$map["Asia/Shanghai"]		= "Asia/Chongqing";
		$map["Asia/Singapore"]		= "Asia/Kuala_Lumpur";
		$map["Australia/Sydney"]	= "Australia/Canberra";
		$map["Pacific/Port_Moresby"]	= "Pacific/Guam";
		$map["Asia/Kamchatka"]		= "Asia/Anadyr";

		return $map;
	}


	function timezones_init(){

		$GLOBALS['_timezones_label_map'] = array();

		$list = timezones_list();
		foreach ($list as $row){
			$GLOBALS['_timezones_label_map'][$row[1]] = $row;
		}
	}

	function timezones_filter($str){

		if (isset($GLOBALS['_timezones_label_map'][$str])) return $str;

		return null;
	}

	#
	# Retrieve the proper label of a timezone, at timestamp $ts (default to now).
	#

	function timezones_label($id, $ts = false){

		$row =& $GLOBALS['_timezones_label_map'][$id];

		if (!$row['lbl']){

			if ($row[4]){

				date_default_timezone_set($id);
				$is_dst = $ts ? date('I', $ts) : date('I');
				date_default_timezone_set($GLOBALS['cfg']['our_tz']);

				$row['lbl'] = $is_dst ? $row[4] : $row[3];
			}else{
				$row['lbl'] = $row[3];
			}
		}

		return $row['lbl'];
	}
